import { z } from 'zod';

import { contentDocSchema, type ContentDoc } from '@/lib/content/schema';
const draftContentSchema = contentDocSchema.refine((doc) =>
  doc.content.every(
    (node) => node.type !== 'heading' || node.attrs.level === 2 || node.attrs.level === 3
  )
);
// Opaque: seeded and migrated drafts carry tokens that are not UUIDs, and every
// writer of the draft row must accept them to take part in the same CAS.
export const draftTokenSchema = z.string().nullable();
// Generated by the client per attempt, so a retry can prove it is the attempt
// that already landed (ADR-0035).
export const nextTokenSchema = z.uuid();
export const saveDraftSchema = z.strictObject({
  postId: z.string().min(1),
  localizationId: z.string().min(1),
  draftToken: draftTokenSchema,
  nextToken: nextTokenSchema,
  title: z.string().max(300),
  excerpt: z.string().max(1000).nullable(),
  contentJson: draftContentSchema,
});
export type SaveDraftInput = z.infer<typeof saveDraftSchema>;
export type EditorDraft = Omit<SaveDraftInput, 'postId' | 'localizationId' | 'nextToken'> & {
  seoTitle?: string | null;
  seoDescription?: string | null;
  canonicalUrl?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImageMediaId?: string | null;
  ogImageAlt?: string | null;
};
export type EditorLocalizations = Partial<Record<'es' | 'en', string>>;

// Checks editor output against the contract the server enforces, so an edit it
// would reject is caught before it is queued. Issues name a path and a code
// only: they end up in the console, and the document text must not.
export function parseDraftContent(
  value: unknown
): { success: true; data: ContentDoc } | { success: false; issues: string[] } {
  const result = draftContentSchema.safeParse(value);
  if (result.success) return { success: true, data: result.data };
  return {
    success: false,
    issues: result.error.issues.map(
      ({ path, code }) => `${['doc', ...path.map(String)].join('.')}: ${code}`
    ),
  };
}
